const data = {
  products: [
    {
      _id: '1',
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/Images/work.jpeg', //679 x 829
      price: 25,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      _id: '2',
      name: 'Lululemon training shirt',
      slug: 'Lululemon-training-shirt',
      category: 'shirts',
      image: '/Images/work.jpeg',
      price: 75,
      countInStock: 60,
      brand: 'Lululemon',
      rating: 5.0,
      numReviews: 332,
      description: 'Uber high quality shirt',
    },
    {
      _id: '3',
      name: 'Lululemon dress pants',
      slug: 'Lululemon-dress-pants',
      category: 'Pants',
      image: '/Images/work.jpeg',
      price: 125,
      countInStock: 33,
      brand: 'Lululemon',
      rating: 5.0,
      numReviews: 32,
      description: 'Uber high quality Pants',
    },
    {
      _id: '4',
      name: 'Birddogs training shorts',
      slug: 'Birddogs-training-shorts',
      category: 'shorts',
      image: '/Images/work.jpeg',
      price: 55,
      countInStock: 2,
      brand: 'Birddogs',
      rating: 4.0,
      numReviews: 32,
      description: 'High quality shorts',
    },
  ],
};

export default data;
